spring:
  application:
    name: demo1
  kafka:
    bootstrap-servers: kafka-svc:9093
    template:
      default-topic: base-event
    consumer:
      group-id: demo1-group
      auto-offset-reset: latest
data:
  test: 김상진

