###############################
####### For Streamsets

apiVersion: v1
kind: PersistentVolume
metadata:
  name: streamsets-data-pv
  labels:
    type: streamsets-data-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-06a10d58077673e7b::fsap-098074ac52f06f74f
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: streamsets-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: streamsets-data-pv
---
